"""Capacity scheduler for VAE training with controlled KL divergence growth.

This module implements a scheduler that gradually increases the KL divergence capacity
during VAE training to prevent posterior collapse while maintaining good reconstruction quality.

Attention:
    This documentation is generated by AI. Please be aware of possible inaccurcies.

"""

import logging
import numpy as np
from typing import Optional, Callable

class capacity_scheduler:
    """Schedule the KL divergence capacity for VAE bottleneck layer.
    
    Gradually increases the target KL divergence (capacity) to allow the model to
    learn meaningful latent representations without posterior collapse. The capacity
    increases when validation loss plateaus, encouraging the model to use more of
    the latent space.
    
    Attributes:
        patience: Number of epochs to wait before increasing capacity after loss plateau.
        capacity: Current KL divergence capacity target.
        capacity_max: Maximum capacity value (stops increasing after reaching this).
        capacity_increment: Amount to increase capacity by (absolute or relative).
        capacity_increment_mode: Either 'abs' (add increment) or 'rel' (multiply by increment).
        counter: Number of epochs since last loss improvement.
        best_score: Best validation loss seen so far.
        threshold: Minimum loss improvement to reset counter.
        threshold_mode: Either 'abs' (absolute threshold) or 'rel' (relative threshold).
        enabled: If False, scheduler is disabled and returns None for capacity.
        reached_max_capacity: True if capacity has reached capacity_max.
    """

    def __init__(
        self, 
        patience: int, 
        capacity_start: float, 
        capacity_max: float, 
        capacity_increment: float, 
        capacity_increment_mode: str, 
        threshold: float, 
        threshold_mode: str, 
        trace_func: Callable = logging.info, 
        enabled: bool = True
    ):
        """Initialize the capacity scheduler.
        
        Args:
            patience: Number of epochs to wait after last validation loss improvement
                before increasing capacity.
            capacity_start: Initial KL divergence capacity target.
            capacity_max: Maximum capacity value (caps further increases).
            capacity_increment: Amount to change capacity when triggered.
            capacity_increment_mode: Either 'abs' (additive: capacity += increment) or 
                'rel' (multiplicative: capacity *= increment).
            threshold: Minimum change in validation loss to qualify as improvement.
            threshold_mode: Either 'abs' (absolute: loss < best - threshold) or 
                'rel' (relative: loss < best * (1 - threshold)).
            trace_func: Logging function for status messages (default: logging.info).
            enabled: If False, scheduler is disabled and get_capacity() returns None.
        
        Raises:
            AssertionError: If capacity_increment_mode or threshold_mode are invalid.
        """
        self.patience = patience
        self.capacity = capacity_start
        self.capacity_max = capacity_max
        self.capacity_increment = capacity_increment
        assert capacity_increment_mode in ['abs', 'rel'], 'Invalid capacity increment mode selected.'
        self.capacity_increment_mode = capacity_increment_mode
        self.counter = 0
        self.best_score = np.inf
        self.corresponding_score = None
        self.early_stop = False
        self.threshold = threshold
        self.threshold_mode = threshold_mode
        assert threshold_mode in ['abs', 'rel'], 'Invalid threshold mode selected.'
        self.trace_func = trace_func
        self.enabled = enabled
        self.reached_max_capacity = False
        self.trace_func('CapacityScheduler initialized with patience = {}, capacity = {}, capacity_increment = {}, capacity_increment_mode = {}, threshold = {}, threshold_mode = {}'.format(
            self.patience, self.capacity, self.capacity_increment, self.capacity_increment_mode, self.threshold, self.threshold_mode))
        if not self.enabled:
            self.trace_func('CapacityScheduler disabled.')

    def update(self, score: float):
        """Update scheduler state based on current validation loss.
        
        Tracks validation loss improvements and increases capacity when loss
        plateaus for 'patience' epochs. Capacity increases until reaching
        capacity_max.
        
        Args:
            score: Current validation loss (typically MSE loss).
        
        Side Effects:
            - Updates counter and best_score
            - Increases capacity if patience threshold reached
            - Sets reached_max_capacity flag when maximum is hit
            - Logs capacity changes via trace_func
        """
        if self.enabled and not self.reached_max_capacity:
            _update_flag = False
            
            if self.threshold_mode == 'abs':
                if score < self.best_score - self.threshold:
                    _update_flag = True
            elif self.threshold_mode == 'rel':
                if score < self.best_score * (1 - self.threshold):
                    _update_flag = True
            
            if _update_flag:
                self.best_score = score
                self.counter = 0
            else:
                self.counter += 1
            
            if self.counter >= self.patience:
                if self.reached_max_capacity is False:
                    # update capacity
                    if self.capacity_increment_mode == 'abs':
                        new_capacity = self.capacity + self.capacity_increment
                    elif self.capacity_increment_mode == 'rel':
                        new_capacity = self.capacity * self.capacity_increment
                    if new_capacity > self.capacity_max:
                        new_capacity = self.capacity_max
                        self.reached_max_capacity = True
                        self.trace_func('\tCapacityScheduler reached maximum capacity of {}.'.format(self.capacity_max))
                    self.capacity = new_capacity

                    self.trace_func('\tCapacityScheduler updated capacity to {} after {} epochs.'.format(self.capacity, self.counter))
                    self.counter = 0

    def get_capacity(self) -> Optional[float]:
        """Get current capacity target for KL divergence loss.
        
        Returns:
            Current capacity value (float) if enabled, None if disabled.
        """
        return self.capacity if self.enabled else None